name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore module cache
        id: module-cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Build tcpmessage
        run: go build -v ./pkg/tcpmessage

      - name: Build tcpserver
        run: |
          go build -v ./pkg/tcpserver
          go build -v ./cmd/tcpserver

      - name: Build tcpclient
        run: |
          go build -v ./pkg/tcpclient
          go build -v ./cmd/tcpclient
