name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore module cache
        id: module-cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Run coverage
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go test ./pkg/tcpmessage ./pkg/tcpclient ./pkg/tcpserver -v -covermode=count -coverprofile=./coverage.out

      - name: Refresh goreport
        uses: creekorful/goreportcard-action@v0.4

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: ./coverage.lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
